apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-echo-pod
  labels:
    app: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: echo-pod
        image: anvesh35/echo-pod-name
